default_language_version:
  python: python3.11
default_stages:
  - commit
  - push
exclude: >
  (?x)^(
      .*/migrations/[0-9]{4}_.*\.py
      | .*/alembic/versions/.*\.py
      | alembic/env.py
      | alembic/versions/.*
      | .*/alembic/.*\.py
      | .*test.*
      | app/adapters/database/models/__init__.py
  )$
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8
          - --ignore=W503
        exclude: (tests|\.code_quality)
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args:
          - --rcfile=.code_quality/.pylintrc
        exclude: (tests|\.code_quality|alembic/versions)
        verbose: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.14
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.1
  #   hooks:
  #     - id: bandit
  #       args:
  #         - -c
  #         - .code_quality/bandit.yaml
  #       exclude: .*\/messages_response\.py
